### ISSUE TITLE
FR: Default Group & Status

### ISSUE THREAD

**Issue by bymayo** [ssplugin/ss-user-import-export#1]
It would be good if you could choose the default group and status for a user when importing them.

It was quite difficult to add the group and status to the CSV file.

Maybe something similar to how Feed Me works:

![Screenshot 2020-06-30 at 12 15 35](https://user-images.githubusercontent.com/522877/86120002-6e4eb200-bacb-11ea-80ed-c82b57fb4ff1.png)

**Comment by ssplugin** [comment]
@bymayo 
We will consider your suggestion in our next plugin update.

Thanks

**Comment by ssplugin** [comment]
@bymayo 
Heyy,
We have released a new version of our plugin `1.0.2`. 
Default group and status field mapping for a user when importing them.
