### ISSUE TITLE
Errors when 'allowAdminChanges' => false

### ISSUE THREAD

**Issue by watarutmnh** [ssplugin/ss-user-import-export#4]
It seems to have an error when uploading CSV file to import when `'allowAdminChanges' => false,` in general.php.
Does it have limitation for use of such a condition?

**Comment by watarutmnh** [comment]
the error message is :

Not Supported – yii\base\NotSupportedException
Changes to the project config are not possible while in read-only mode.

**Comment by ssplugin** [comment]
@watarutmnh 
If you disable `'allowAdminChanges'` then you are no longer to access CP therefore you can't able to create a new user.
It is not a plugin limitation but this is a Craft CMS workflow.

**Comment by iainhenderson** [comment]
Hi @watarutmnh disabling allowAdminChanges still allows access to the CP, it just disallows 'administrative' changes (which admittedly isn't super clear wording)

From  https://craftcms.com/docs/3.x/config/config-settings.html#allowadminchanges 

> When this is disabled, the Settings section will be hidden, the Craft edition and Craft/plugin versions will be locked, and the project config and Plugin Store will become read-only—though Craft and plugin licenses may still be purchased.

You can still create new users when allowAdminChanges is disabled. The problem I believe is the locked project config. The plugin copies the latest import data there, I haven't looked into why it needs that yet. If allowAdminChanges is disabled - as the Craft 3.5+ docs recommend it should be on the production server - the plugin isn't allowed to write the import data to the project config, and throws that error.

As a side note the plugin allows the import of passwords, which means user emails and passwords could now be stored as plain text in the project.yaml file on the server, which is a potential security issue. I know project.yaml shouldn't be publicly accessible but it's still probably a bad idea. If the last Import information doesn't need to be stored in project config I would suggest removing it to solve both problems.

**Comment by watarutmnh** [comment]
@ssplugin @iainhenderson 
Thanks for the support. Excuse me that i have been response quite while.
Now I understand the Craft CMS workflow and the security risk.
I imported users at local development and copy database to production and it is OK.

**Comment by iainhenderson** [comment]
Hi @watarutmnh I think this issue may need to be reopened. I'm glad my explanation helped you find a work around, but other users are likely to experience the same issues unless the plugin is updated so that import data isn't stored in the project config. @ssplugin I was wondering if storing import data in the config is required?

**Comment by ssplugin** [comment]
@iainhenderson 
Thanks for the explanation. Yes about project config data save concern, we will look at the other way how can be possible without store data.

**Comment by watarutmnh** [comment]
Okay I will reopen this issue so that we can follow the issue as it is still on considered.

**Comment by ssplugin** [comment]
@watarutmnh @iainhenderson 
We have committed changes in the new version ( 1.0.3 ). Now you can able to use this plugin when **'allowAdminChanges'**  is false. Data stored in the project config is removed now.
Please check it. ENJOY!!

**Comment by watarutmnh** [comment]
@ssplugin thanks!!

**Comment by iainhenderson** [comment]
That's great @ssplugin thanks for looking into that so quickly.
