### ISSUE TITLE
Default user status does not trigger `sendActivationEmail`

### ISSUE THREAD

**Issue by leevigraham** [ssplugin/ss-user-import-export#6]
These lines do not take into consideration the default values:

https://github.com/ssplugin/ss-user-import-export/blob/master/src/services/SsUserImportExportService.php#L146-L148

```php
if( strtolower($fields['userstatus']) == 'active' || strtolower($fields['userstatus']) == '1'){
    Craft::$app->getUsers()->sendActivationEmail($user);
}
```

They should be changed to:

```php
if( strtolower($userStatus) == 'active' || strtolower($userStatus) == '1'){
    Craft::$app->getUsers()->sendActivationEmail($user);
}
```

**Comment by ssplugin** [comment]
@leevigraham 
Yes, You are right, when default status is selected then the above condition does not work. Thanks for your attention to this issue. It will be added shortly in our next version.

**Comment by ssplugin** [comment]
@leevigraham 
Thank you very much for your request. We have considered your pull request and the new version changed as per your suggestion.
