### ISSUE TITLE
 Import functionality stops

### ISSUE THREAD

**Issue by dolping** [ssplugin/ss-user-import-export#9]
Hi,

  Suddenly the Import functionality of this plugin stops. After I upload a CSV file, it will just redirect to a blank page with text "Please upload a csv file here" and nothing happens https://prnt.sc/1v3ubzt , supposedly it should display the element mapping.

**Comment by ssplugin** [comment]
Hello @dolping,

We have investigated this issue. It looks like a problem with the CSV file.  When you upload a CSV file then file data is not properly formatted or empty files. 
For further more investigation please share your CSV file with us. You can also send your CSV file with our email address: ssplugins.seeders@gmail.com

**Comment by dolping** [comment]
hi, CSV files were already sent to your email please check.

**Comment by ssplugin** [comment]
@dolping Heyy, Thanks for sending CSV files. we have tested all the files and it is working but as you mentioned `test` file not working so please send test files.
Also, we have sent a mail for more details like what is your configuration and error log.
